<?php
/**
 * Font Converter for fonts2web.org.uk
*
* You may not change or alter any portion of this comment or credits
* of supporting developers from this source code or any supporting source code
* which is considered copyrighted (c) material of the original comment or credit authors.
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* @copyright   	The XOOPS Project http://fonts2web.org.uk
* @license     	General Public License version 3 (http://labs.coop/briefs/legal/general-public-licence/13,3.html)
* @author      	Simon Roberts (wishcraft) <wishcraft@users.sourceforge.net>
* @subpackage  	convert
* @description 	Converts fonts to web distributional format in a zip pack stamped
* @version		1.0.1
* @link        	http://fonts2web.org.uk
* @link        	http://fonts.labs.coop
* @link			http://internetfounder.wordpress.com
*/


// Licencing Commonality & Defaults
define('_MD_CONVERT_LICENSE_EXTENSION','eot');
define('_MD_CONVERT_LICENSE_NAME','Creative Commons - Share Alike');
define('_MD_CONVERT_LICENSE_CODE','BY-SA');
define('_MD_CONVERT_LICENSE_URL','https://creativecommons.org/licenses/by-sa/4.0/legalcode');
define('_MD_CONVERT_LICENSE_NOTICE','Generated by %s (%s) on behalf of:\010\010Company: %s\010Name: %s\010eMail: %s\010\010This is licensed under %s which legal transcript can be found at: %s');
define('_MD_CONVERT_VERSION_INCREMENT',1.001);
define('_MD_CONVERT_DEFAULT_COMPANY','Chronolabs (Australia)');
define('_MD_CONVERT_RELEASE_TWEET','Zero-day Font: %s (%s Mb) %s via @%s');

// Path information
define('_MD_CONVERT_PATH_UPLOADS',DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'fonts4web');
define('_MD_CONVERT_PATH_CACHE',XOOPS_VAR_PATH . DIRECTORY_SEPARATOR . 'caches' . DIRECTORY_SEPARATOR . 'fonts4web');
define('_MD_CONVERT_PATH_REPOSITORY',XOOPS_VAR_PATH . DIRECTORY_SEPARATOR . 'fonts4web' . DIRECTORY_SEPARATOR . 'respository');

// Admin Dashboard
define('_MD_CONVERT_ADMIN_STATISTICS','Font Conversion Statistics');
define('_MD_CONVERT_ADMIN_STATS_TOTALUPLOADS','Total Fonts Uploaded: %s');
define('_MD_CONVERT_ADMIN_STATS_TOTALDOWNLOADS','Total Packs Downloaded: %s');
define('_MD_CONVERT_ADMIN_STATS_TOTALDOWNLOADSMBS','Total Megabytes Downloaded: %s');
define('_MD_CONVERT_ADMIN_STATS_FILESINCACHE','Total Files in Cache: %s');
define('_MD_CONVERT_ADMIN_STATS_MBSINCACHE','Total Megabytes store in Cache: %s');
define('_MD_CONVERT_ADMIN_STATS_FILESINREPO','Total files in Repository: %s');
define('_MD_CONVERT_ADMIN_STATS_MBSINREPO','Total Megabytes in Repository: %s');

// Module Admin Menu
define('_MD_CONVERT_ADMINMENU_HOME','Font Converter Home');
define('_MD_CONVERT_ADMINMENU_FONTS','Uploaded Fonts');
define('_MD_CONVERT_ADMINMENU_ABOUT','Font Converter About');

// Module definition headers for xoops_version.php
define('_MD_CONVERT_MODULE_NAME','Font Coverter');
define('_MD_CONVERT_MODULE_VERSION','6.66');
define('_MD_CONVERT_MODULE_RELEASEDATE','');
define('_MD_CONVERT_MODULE_STATUS','release');
define('_MD_CONVERT_MODULE_DESCRIPTION','Font convert is a module which converts and packages web fonts!');
define('_MD_CONVERT_MODULE_CREDITS','Mynamesnot, Wishcraft');
define('_MD_CONVERT_MODULE_AUTHORALIAS','wishcraft');
define('_MD_CONVERT_MODULE_HELP','page=help');
define('_MD_CONVERT_MODULE_LICENCE','gpl3+academic');
define('_MD_CONVERT_MODULE_OFFICAL','0');
define('_MD_CONVERT_MODULE_ICON','images/modlogo.png');
define('_MD_CONVERT_MODULE_WEBSITE','http://au.syd.labs.coop');
define('_MD_CONVERT_MODULE_ADMINMODDIR','/Frameworks/moduleclasses/moduleadmin');
define('_MD_CONVERT_MODULE_ADMINICON16','../../Frameworks/moduleclasses/icons/16');
define('_MD_CONVERT_MODULE_ADMINICON32','./../Frameworks/moduleclasses/icons/32');
define('_MD_CONVERT_MODULE_RELEASEINFO',__DIR__ . DIRECTORY_SEPARATOR . 'release.nfo');
define('_MD_CONVERT_MODULE_RELEASEXCODE',__DIR__ . DIRECTORY_SEPARATOR . 'release.xcode');
define('_MD_CONVERT_MODULE_RELEASEFILE','https://sourceforge.net/projects/chronolabs/files/XOOPS%202.5/Modules/please/xoops2.5_please_1.05.7z');
define('_MD_CONVERT_MODULE_AUTHORREALNAME','Simon Antony Roberts');
define('_MD_CONVERT_MODULE_AUTHORWEBSITE','http://internetfounder.wordpress.com');
define('_MD_CONVERT_MODULE_AUTHORSITENAME','Exhumations from the desks of Chronographics');
define('_MD_CONVERT_MODULE_AUTHOREMAIL','simon@staff.labs.coop');
define('_MD_CONVERT_MODULE_AUTHORWORD','');
define('_MD_CONVERT_MODULE_WARNINGS','');
define('_MD_CONVERT_MODULE_DEMO_SITEURL','');
define('_MD_CONVERT_MODULE_DEMO_SITENAME','');
define('_MD_CONVERT_MODULE_SUPPORT_SITEURL','');
define('_MD_CONVERT_MODULE_SUPPORT_SITENAME','');
define('_MD_CONVERT_MODULE_SUPPORT_FEATUREREQUEST','');
define('_MD_CONVERT_MODULE_SUPPORT_BUGREPORTING','');
define('_MD_CONVERT_MODULE_DEVELOPERS','Simon Roberts (Wishcraft)'); // Sperated by a Pipe (|)
define('_MD_CONVERT_MODULE_TESTERS',''); // Sperated by a Pipe (|)
define('_MD_CONVERT_MODULE_TRANSLATERS',''); // Sperated by a Pipe (|)
define('_MD_CONVERT_MODULE_DOCUMENTERS',''); // Sperated by a Pipe (|)
define('_MD_CONVERT_MODULE_HASSEARCH',true);
define('_MD_CONVERT_MODULE_HASMAIN',true);
define('_MD_CONVERT_MODULE_HASADMIN',true);
define('_MD_CONVERT_MODULE_HASCOMMENTS',true);

// Configguration Categories
define('_MD_CONVERT_CONFCAT_SEO','Search Engine Optimization');
define('_MD_CONVERT_CONFCAT_SEO_DESC','');
define('_MD_CONVERT_CONFCAT_MODULE','Font Converter Module Settins');
define('_MD_CONVERT_CONFCAT_MODULE_DESC','');
define('_MD_CONVERT_CONFCAT_TWITTER','Font Converter Twitter API Setting');
define('_MD_CONVERT_CONFCAT_TWITTER_DESC','');


// Configuration Descriptions and Titles
define('_MD_CONVERT_HTACCESS','.htaccess SEO URL');
define('_MD_CONVERT_HTACCESS_DESC','');
define('_MD_CONVERT_BASE','base .htaccess path');
define('_MD_CONVERT_BASE_DESC','');
define('_MD_CONVERT_HTML','extension for HTML output with SEO URL');
define('_MD_CONVERT_HTML_DESC','');
define('_MD_CONVERT_COMPLEXITY_IMAGES','Number of Maximum Background images with "complexity" theme');
define('_MD_CONVERT_COMPLEXITY_IMAGES_DESC','Periodically the number of buffered images as previews is check and culled when higher than this number, this is done at random!');
define('_MD_CONVERT_COMPLEXITY_MAXDELETED','Number of Maximum Background images deleted when image count is greater than the maximum allowed');
define('_MD_CONVERT_COMPLEXITY_MAXDELETED_DESC','This is done at random, however this is the maximum amount that will be randomly deleted when limit is reached!');
define('_MD_CONVERT_SYNDICATE','Syndicate with API');
define('_MD_CONVERT_SYNDICATE_DESC','This will syndicate with http://fonts.labs.coop fonting repository API!');
define('_MD_CONVERT_SYNDICATE_DELAY','Syndication Delay');
define('_MD_CONVERT_SYNDICATE_DELAY_DESC','Number of seconds to wait between sydnication attempts, this only happens once per title of font!');
define('_MD_CONVERT_CACHE_SECONDS','Cache Survives for Minimal Seconds');
define('_MD_CONVERT_CACHE_SECONDS_DESC','This is how long a cache file will stay around!');
define('_MD_CONVERT_TWITTER_USERNAME','The Twitter Username for the Site');
define('_MD_CONVERT_TWITTER_USERNAME_DESC','');
define('_MD_CONVERT_TWITTER_ACCESS_TOKEN','The Twitter API Access Token');
define('_MD_CONVERT_TWITTER_ACCESS_TOKEN_DESC','Your key for an application needs to be generated and taken with write permission from http://apps.twitter.com!');
define('_MD_CONVERT_TWITTER_ACCESS_SECRET','The Twitter API Access Token Secret');
define('_MD_CONVERT_TWITTER_ACCESS_SECRET_DESC','Your key for an application needs to be generated and taken with write permission from http://apps.twitter.com!');
define('_MD_CONVERT_TWITTER_CONSUMER_TOKEN','The Twitter API Consumer Key');
define('_MD_CONVERT_TWITTER_CONSUMER_TOKEN_DESC','Your key for an application needs to be generated and taken with write permission from http://apps.twitter.com!');
define('_MD_CONVERT_TWITTER_CONSUMER_SECRET','The Twitter API Consumer Secret');
define('_MD_CONVERT_TWITTER_CONSUMER_SECRET_DESC','Your key for an application needs to be generated and taken with write permission from http://apps.twitter.com!');
